const GET_DOGS = 'GET_DOGS';
const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';
const FILTER_CREATED = 'FILTER_CREATED';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const GET_TEMPERAMENTS_LIST ="GET_TEMPERAMENTS_LIST";
const GET_DOGS_BY_TEMP="GET_DOGS_BY_TEMP";
module.exports = { GET_DOGS,FILTER_BY_TEMPERAMENT,FILTER_CREATED, ORDER_BY_NAME,GET_TEMPERAMENTS_LIST,GET_DOGS_BY_TEMP}


