const GET_DOGS = 'GET_DOGS';
const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';
const FILTER_CREATED = 'FILTER_CREATED';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const GET_TEMPERAMENTS_LIST ="GET_TEMPERAMENTS_LIST";
const GET_DOGS_BY_TEMP="GET_DOGS_BY_TEMP";
const ORDER_BY_WEIGHT= 'ORDER_BY_WEIGHT'
const GET_NAME_DOGS = 'GET_NAME_DOGS';
module.exports = { GET_DOGS,
    FILTER_BY_TEMPERAMENT,
    FILTER_CREATED, 
    ORDER_BY_NAME,GET_TEMPERAMENTS_LIST,
    GET_DOGS_BY_TEMP,
    ORDER_BY_WEIGHT,
    GET_NAME_DOGS}


